// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/advocates-demo/AdvocatesDemo.tsx": () => import("../components/mockups/advocates-demo/AdvocatesDemo.tsx"),
  "./components/mockups/advocates-demo/FbShareAd.tsx": () => import("../components/mockups/advocates-demo/FbShareAd.tsx")
};
